---
# playbook for setting up the admin account with stuff I like to work with
# pass in a specific host of group of hosts when calling this playbook. This keeps
# the playbook non-destructive except for explicitly defined hosts. 

- hosts: '{{ target }}'
  user: '{{ admin_user }}'

  roles:
    - global-prefs
    - homebrew

  pre_tasks: 
    - set_fact: user_home=/Users/{{ ansible_ssh_user }}
    - set_fact: user_lib={{ user_home }}/Library
    - set_fact: user_lib_prefs={{ user_lib }}/Preferences

    - name: Make sure User icons directory exists
      file: path=/Library/User\ Pictures/IOP/ state=directory mode=0755
      sudo: yes

    - name: Send new account picture
      copy: src=roles/new-user/files/IOP-logo-for-accounts-admin.png dest=/Library/User\ Pictures/IOP/IOP-logo-for-accounts-admin.png mode=0644
      sudo: yes

    - name: Update user account picture
      command: 'dscl . {{ item }}'
      with_items:
        - delete /Users/iop jpegphoto
        - delete /Users/iop Picture
        - create /Users/iop Picture "/Library/User Pictures/IOP/IOP-logo-for-accounts-admin.png"
      sudo: yes

    - name: Prepend /usr/local/bin to $PATH in .profile
      lineinfile: 'dest=/Users/{{ ansible_ssh_user }}/.profile state=present regexp="^export\s+PATH=/usr/local/bin:\\$PATH" insertafter=EOF line="export PATH=/usr/local/bin:$PATH" create=yes'

    - name: add WORKON_HOME to .profile
      lineinfile: 'dest=/Users/{{ ansible_ssh_user }}/.profile state=present regexp="^export\s+WORKON_HOME=" insertafter=EOF line="export WORKON_HOME=$HOME/.virtualenvs" create=yes'

    - name: add VIRTUALENVWRAPPER_VIRTUALENV_ARGS to .profile
      lineinfile: 'dest=/Users/{{ ansible_ssh_user }}/.profile state=present regexp="^export\s+VIRTUALENVWRAPPER_VIRTUALENV_ARGS=" insertafter=EOF line="export VIRTUALENVWRAPPER_VIRTUALENV_ARGS=\"--no-site-packages\"" create=yes'

    - name: source virtualenvwrapper from .profile
      lineinfile: 'dest=/Users/{{ ansible_ssh_user }}/.profile state=present regexp="^source .*virtualenvwrapper.sh$" insertafter=EOF line="source /usr/local/bin/virtualenvwrapper.sh" create=yes'
      tags: pip

    - name: 'Finder: Very fast keyboard repeat'
      shell: defaults write {{ user_lib_prefs }}/.GlobalPreferences KeyRepeat -int 0

    - name: 'Finder: Initial KeyRepeat delay'
      shell: defaults write {{ user_lib_prefs }}/.GlobalPreferences InitialKeyRepeat -int 25

    - name: 'Finder: Set sidebar icon size to small'
      shell: defaults write {{ user_lib_prefs }}/.GlobalPreferences NSTableViewDefaultSizeMode -int 1

    - name: "Finder: Show status bar"
      shell: defaults write {{ user_lib_prefs }}/com.apple.finder ShowStatusBar -bool true

    - name: 'Finder: Enable Airdrop on all network interfaces'
      shell: defaults write {{ user_lib_prefs }}/com.apple.NetworkBrowser BrowseAllInterfaces -bool true

    - name: 'Finder: Show all files'
      shell: defaults write {{ user_lib_prefs }}/com.apple.finder AppleShowAllFiles -bool true

    - name: 'Finder: Empty the Desktop folder'
      shell: find {{ user_home}}/Desktop -mindepth 1 -delete

    - name: Kill Dock
      command: killall Dock
      ignore_errors: yes
      sudo: yes

    - name: Repair permissions
      shell: "chown -R {{ ansible_ssh_user }}:staff {{ user_lib_prefs }}/"
      sudo: yes

  post_tasks:
    - name: Install virtualenvwrapper
      pip: name=virtualenvwrapper
      environment:
        PATH: /usr/local/bin:{{ ansible_env["PATH"] }}
      sudo: yes
      tags: pip

    - name: Copy terminal settings file
      copy: src=files/smoke.terminal dest=/tmp/smoke.terminal
      tags: terminal

    - name: Set default terminal
      command: open /tmp/smoke.terminal
      ignore_errors: yes
      tags: terminal

    - name: 'Terminal: Set startup window'
      shell: 'defaults write {{ user_lib_prefs }}/com.apple.Terminal "Startup Window Settings" -string smoke'
      tags: terminal

    - name: 'Terminal: Set default window'
      shell: 'defaults write {{ user_lib_prefs }}/com.apple.Terminal "Default Window Settings" -string smoke'
      tags: terminal
