---
# playbook for creating new users at IOP
# this only sets up the user, configuration is handled by another playbook.
- hosts: '{{ target }}'
  user: '{{ admin_user }}'
  sudo: yes

# This file contains login/password info, recreate it for specific runs
  vars_files:
    - vars/user.yml

  pre_tasks:
    - name: Check if user exists
      stat: path=/Users/{{ username }}
      register: user_stat

    - set_fact: user_exists={{ user_stat.stat.exists }}

    - set_fact: user_home=/Users/{{ username }}
    - set_fact: user_lib=/Users/{{ username }}/Library
    - set_fact: user_lib_prefs={{ user_lib }}/Preferences

  roles:
    - global-prefs
    - new-user
    - safari
    - finder
    - mail

  post_tasks:
    - name: Parse the Markdown template
      shell: python -m markdown -x extra -x smarty welcome.md > welcome.html.j2 chdir=templates
      connection: local
      sudo: no

    - name: Generate Welcome message on controller
      template: src=templates/welcome.html.j2 dest=./Welcome-to-IOP_{{ username }}.html
      connection: local
      sudo: no

    - name: Remove generated template
      file: path=templates/welcome.html.j2 state=absent
      connection: local
      sudo: no

  vars:
    account_icons:
      - IOP-logo-for-accounts-blue.png
      - IOP-logo-for-accounts-brown.png
      - IOP-logo-for-accounts-green.png
