---

- name: Check that Vagrant is installed
  stat: path=/usr/local/bin/vagrant
  become: no
  tags: [vagrant]
  register: vagrant_installed 

- name: Install additional Vagrant plugins
  shell: '{{ vagrant_installed.stat.path }} plugin install {{ item }}'
  become_user: '{{ ansible_user_id }}'
  tags: [vagrant]
  when: vagrant_installed.stat.exists
  with_items:
    - vagrant-hostmanager
    - vagrant-bindfs

- name: Install sudoers.d file for password-free vagrant up with vagrant-hostmanager
  become: yes
  get_url:
    url: 'https://gist.githubusercontent.com/joemaller/41912f5d027a4adc7c14/raw'
    dest: '/etc/sudoers.d/vagrant-hostmanager-nopasswd'
    owner: root
    group: wheel
    mode: 0400
