---

- name: Check that Vagrant is installed
  stat: path=/usr/local/bin/vagrant
  become: no
  tags: [vagrant]
  register: vagrant_installed 

- name: Install additional Vagrant plugins
  shell: '{{ vagrant_installed.stat.path }} plugin install {{ item }}'
  become_user: '{{ ansible_user_id }}'
  tags: [vagrant]
  when: vagrant_installed.stat.exists
  with_items:
    - vagrant-hostsupdater
    - vagrant-bindfs
