---

- name: 'Dock: Enable App Exposé'
  shell: defaults write {{ user_lib_prefs }}/com.apple.dock showAppExposeGestureEnabled -bool true
  when: dock_app_expose
  become: no
  notify:
    - restart dock

- name: 'Dock: Use translucent icons for hidden applications'
  shell: defaults write {{ user_lib_prefs }}/com.apple.dock showhidden -bool true
  when: dock_dim_hidden
  become: no
  notify:
    - restart dock
