---

homebrew_cask_paths:
  - /Library/Caches/Homebrew/Casks
  - /opt/homebrew-cask

apps:
  - adobe-creative-cloud
  - google-chrome
  - kaleidoscope
  - sketch
  - sourcetree
  - sublime-text3
  - transmit
  - vagrant
  - virtualbox
