---

- name: 'Finder: Set sidebar icon size to small'
  shell: defaults write {{ user_lib_prefs }}/.GlobalPreferences NSTableViewDefaultSizeMode -int 1

- name: "Finder: Show status bar"
  shell: defaults write {{ user_lib_prefs }}/com.apple.finder ShowStatusBar -bool true

- name: 'Finder: New Window Target'
  shell: 'defaults write {{ user_lib_prefs }}/com.apple.finder NewWindowTarget -string PfHm'

- name: 'Finder: New Window Target Path'
  shell: 'defaults write {{ user_lib_prefs }}/com.apple.finder NewWindowTargetPath -string file://{{ user_home }}/'

- name: 'Finder: Enable Airdrop on all network interfaces'
  shell: defaults write {{ user_lib_prefs }}/com.apple.NetworkBrowser BrowseAllInterfaces -bool true

- name: 'Finder: Set Dock from template'
  template: src=com.apple.dock.j2 dest={{ user_lib_prefs }}/com.apple.dock.plist

- name: 'Finder: Disable iCloud popup'
  shell: defaults write {{ user_lib_prefs }}/com.apple.SetupAssistant DidSeeCloudSetup -bool true

- name: 'Finder: Disable Gesture movie'
  shell: defaults write {{ user_lib_prefs }}/com.apple.SetupAssistant GestureMovieSeen none

- name: 'Finder: Set last seen cloud version'
  shell: defaults write {{ user_lib_prefs }}/com.apple.SetupAssistant LastSeenCloudProductVersion -string 10.9

- name: Repair permissions
  shell: "chown -R {{ username }}:staff {{ user_lib_prefs }}/"

- name: 'Restart Dock'
  command: killall {{ item }}
  ignore_errors: yes
  with_items: 
    - Dock
    - Finder

