---

- name: Get next available User ID
  shell: "echo $(dscl . -list /Users uid | awk '{print $2}' | sort -ug  | tail -1) + 1 | bc"
  register: uid

- command: mktemp -t create_{{ username }}-XXXXX
  register: newuser_script

- name: Create user script
  template: src=newuser.j2 dest={{ newuser_script.stdout }} mode=0755

- name: Make a user!
  shell: "{{ newuser_script.stdout }} creates=/Users/{{ username }}"

- name: Remove the newuser script
  file: path={{ newuser_script.stdout }} state=absent

- name: Prepend /usr/local/bin to $PATH in .profile
  lineinfile:
    dest=/Users/{{ username }}/.profile
    state=present
    regexp="^export\s+PATH=/usr/local/bin:\\$PATH"
    insertafter=EOF
    line="export
    PATH=/usr/local/bin:$PATH"
    create=yes
