---

- name: Get next available User ID
  shell: "echo $(dscl . -list /Users uid | awk '{print $2}' | sort -ug  | tail -1) + 1 | bc"
  register: uid

- name: Use a uuid for the script name
  shell: "date | shasum -a 384 | awk '{print $1}'" 
  register: script_name

- set_fact: 'newuser_sh={{ script_name.stdout }}.sh'

- name: Create user script
  template: src=newuser.j2 dest=/tmp/{{ newuser_sh }} mode=0755

- name: Make a user!
  shell: /tmp/{{ newuser_sh }} creates=/Users/{{ username }}

- name: Remove the newuser script
  file: path=/tmp/{{ newuser_sh }} state=absent

- name: Prepend /usr/local/bin to $PATH in .profile
  lineinfile:
    dest=/Users/{{ username }}/.profile
    state=present
    regexp="^export\s+PATH=/usr/local/bin:\\$PATH"
    insertafter=EOF
    line="export
    PATH=/usr/local/bin:$PATH"
    create=yes
