---
- name: Homebrew installs
  environment:
    PATH: /usr/local/bin:{{ ansible_env["PATH"] }}
  homebrew: name={{ item }}
  with_items:
    - git
    - python
    - python3
    # - nodejs
    # node seems to install but returns an error, breaking the playbook