---

- name: Make sure Homebrew directory exists
  file: 
    path=/usr/local/*
    state=directory
    mode=0775
    owner=root
    group=wheel
    recurse=yes
  become: yes

- name: Download Homebrew
  unarchive:
    src: 'https://github.com/Homebrew/brew/archive/master.zip'
    dest: /tmp/
    remote_src: yes
    
- name: move Homebrew files to /usr/local
  synchronize: 
    src: /tmp/brew-master/
    dest: /usr/local/
  delegate_to: "{{ inventory_hostname }}"
  become: yes

- name: Set permissions for multiple users
  file: 
    path={{ item }}
    mode=0775
    owner=root
    group=admin
    recurse=yes
    state=directory
  become: yes
  with_items: '{{ homebrew_paths }}'

- name: Fix ACL permissions for multiple users
  become: yes
  command: 'chmod -R +a "group:admin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" {{ item }}'
  with_items: '{{ homebrew_paths }}'

- name: Reset the Homebrew Library repo
  git: 
    repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: no
  ignore_errors: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: no
